- name : datatypes
  connection : local
  hosts : local
  vars :
    Course: DevOps with AWS
    Duration: 10HRS
    is_live: true # boolean
    Trainer: reddy
    tools:
    - "linux"  
    - "aws"
    - "ansible"
    concepts :
      cloud : aws
      comm : ansible
  tasks:
    - name : print course info 
      ansible.builtin.debug:
        msg: "Course name: {{ Course }}, Duration: {{ Duration }}, is it live?: {{ is_live }}, tools are: {{ tools }} concepts are: {{ concepts }}"
    